title: Andrew Mendez # your name (or website title) here
logo: "/images/blacksweaterhead.jpg?raw=true" # your photo (or logo) here
description: 

Welcome!<br>
My name is Andrew and I am currently making a pivot from 10 years in the Hospitality Industry into the world of data! I extremely motived and excited about this change and I've been currently refining skills in Excel, SQL, Tableau, and Python. Below you can click on the Data Tool Icon to see the projects I've done using those tools. To the right here are all the projects beginning with the most recent!
<br>

I'm actively seeking a Data Analyst position! My email is available below! Thank you for visiting!
<br><br>

href="images/favicon.ico"

<a href="https://www.linkedin.com/in/andrewjosephmendez/">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
