title: Andrew Mendez

logo: "/images/blacksweaterhead.jpg?raw=true"

description: 
👋 Hi, I’m Andrew — a data-driven professional with a passion for turning messy problems into actionable insights. My GitHub portfolio highlights projects in data cleaning, analysis, and visualization, with a focus on business impact and real-world application.

📊 With a background in high-performance operations and team leadership, I bring a unique edge to data work: sharp analytical thinking, stakeholder empathy, and a bias toward clarity and execution. I love using Python, SQL, and Excel to make data not just readable — but meaningful.

🧰 Tools I work with: Python (Pandas, NumPy, Matplotlib, Seaborn), SQL, Jupyter Notebooks, Excel/PowerQuery, and a growing toolkit in BI and data storytelling.

🚀 Always exploring new datasets, new tools, and new ways to add value through data.
  
<br><br>
      <style>
        .libutton {
          display: flex;
          flex-direction: column;
          justify-content: center;
          padding: 7px;
          text-align: center;
          outline: none;
          text-decoration: none !important;
          color: #ffffff !important;
          width: 200px;
          height: 32px;
          border-radius: 16px;
          background-color: #0A66C2;
          font-family: "SF Pro Text", Helvetica, sans-serif;
        }
      </style>
<a class="libutton" href="https://www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=andrewmendezdata" target="_blank">Follow on LinkedIn</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
