title: Andrew Mendez # your name (or website title) here
logo: "/images/blacksweaterhead.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome!<br>
  My name is Andrew and I am currently transitioning into the world of data from 10+ years in the restaurant industry. Here are the projects I've been working on!
  
  <br><br>
  <a href="https://www.linkedin.com/in/andrewjosephmendez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
