title: Andrew Mendez # your name (or website title) here
logo: "/images/blacksweaterhead.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Welcome!<br>
My name is Andrew and I am currently making a pivot from 10 years in the Hospitality Industry into the world of data! To the right here are all the projects beginning with the most recent!
<br>

<a href="https://www.linkedin.com/in/andrewmendezdata/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
